### ISSUE TITLE
Dmenu support

### ISSUE THREAD

**Issue by asmallcarrot** [PlankCipher/rofi_et#1]
### Feature Request

I have been trying to convert this script to work with dmenu but so far have been unsuccessful, I would like to see if it would be possible to make a port.

**Comment by PlankCipher** [comment]
I was kinda sure this will come up, so I already started extracting the core functionality of the script to another script that outputs just text streams so that it can then be reused with `rofi`, `dmenu`, or any other program. I will make sure I make a `dmenu` version of it.

**Comment by PlankCipher** [comment]
Commit e498187 introduces a text-only cli tool and commit b1a9965 adds dmenu support.
